- name: Install wireguard service
  include_tasks: install.yml
  args:
    apply:
      become: true
      become_user: root
      when: not flush_all

- name: Remove wireguard service
  include_tasks: uninstall.yml
  args:
    apply:
      become: true
      become_user: root
      when: flush_all
